"""
templates.py

BRN HTML 템플릿
"""

from datetime import datetime


def html_header(title="BRN 부동산 뉴스 브리핑"):
    """HTML 헤더"""

    today = datetime.now().strftime("%Y-%m-%d")

    return f"""<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>

<style>

body {{
    margin:0;
    padding:0;
    background:#f5f5f5;
    font-family:Arial, Helvetica, sans-serif;
}}

.container {{
    width:95%;
    max-width:1200px;
    margin:auto;
}}

header {{
    background:#005bac;
    color:white;
    padding:20px;
}}

header h1 {{
    margin:0;
}}

header p {{
    margin-top:8px;
}}

.summary {{
    background:white;
    padding:15px;
    margin:20px 0;
    border-radius:8px;
}}

.category {{
    background:white;
    margin:20px 0;
    border-radius:8px;
    overflow:hidden;
}}

.category-title {{
    background:#0067c5;
    color:white;
    padding:12px;
    font-size:20px;
    font-weight:bold;
}}

.news-list {{
    padding:15px;
}}

.news-item {{
    padding:10px 0;
    border-bottom:1px solid #e0e0e0;
}}

.news-item:last-child {{
    border-bottom:none;
}}

.news-item a {{
    color:#222;
    text-decoration:none;
    font-weight:bold;
}}

.news-item a:hover {{
    color:#0067c5;
}}

.source {{
    margin-left:10px;
    color:#888;
    font-size:13px;
}}

footer {{
    margin:40px 0;
    text-align:center;
    color:#777;
}}

</style>

</head>

<body>

<div class="container">

<header>
<h1>{title}</h1>
<p>{today}</p>
</header>
"""


def html_footer():
    """HTML 푸터"""

    return """
<footer>
<p>Generated by BRN Project</p>
</footer>

</div>

</body>
</html>
"""


def section_header(title):
    """카테고리 시작"""

    return f"""
<section class="category">

<div class="category-title">
{title}
</div>

<div class="news-list">
"""


def section_footer():
    """카테고리 종료"""

    return """
</div>
</section>
"""
