name: Daily News Update
on:
  schedule:
    - cron: '0 0 * * *' # 매일 자정 실행
  workflow_dispatch:      # 수동 실행 버튼

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with: {python-version: '3.9'}
      - name: Install dependencies
        run: pip install feedparser
      - name: Generate Index
        run: python generate_news.py
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add index.html
          # 파일 변경사항이 있을 때만 커밋
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update index.html by GitHub Actions" && git push)
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
